### ISSUE TITLE
Generate defualt GPOPS-II settings file not working

### ISSUE THREAD

**Issue by RobSalati** [aymanhab/opensim-gui-rcnl#44]
When selecting the "Generate default settings file" option, no settings file is created, and the field is left blank in the xml.

**Comment by aymanhab** [comment]
Now a file with default name and content is written once the radio button is selected. Not sure the use case or if a dialog to select save destination is necessary, please let me know @RobSalati as well as verify that the file contents are correct

**Comment by RobSalati** [comment]
The xml element is now populated, but the file is still not being saved. 

I think for clarity sake, a dialogue to select the save destination is a good idea.

**Comment by RobSalati** [comment]
Writing the file works almost as intended. The last thing we need is to change the outside tag to specify NMSMPipelineDocument instead of OpenSimDocument as we do with the other tools. @aymanhab

**Comment by RobSalati** [comment]
Do you have any updates on this issue? Please let me know if there's anything I can clear up or help with! @aymanhab

**Comment by aymanhab** [comment]
@RobSalati I believe I fixed this already back in January and was hoping you'd have a local build to test with, but will rebuild my environment to verify locally

**Comment by RobSalati** [comment]
What branch is this change on? I just built on master2 and I still have the issue.

**Comment by RobSalati** [comment]
Closed as completed. Thank you!
